### ISSUE TITLE
when the domain change to another ip the miner do not change to another pool

### ISSUE THREAD

**Issue by ncgege** [XDagger/DaggerGpuMiner#6]
the DaggerGpuminer has a bug ,if the miners mining by domain(eg. xdag.xdpool.com:9988->1.1.1.1:9988),if i change the domain to another ip  2.2.2.2:9988,the daggergpuminer don't change to the new ip(2.2.2.2) ,it still mining on the old one(1.1.1.1) .

**Comment by xrdavies** [comment]
It's DNS issue, clean local dns cache and restart Miner will solve this issue.
